### ISSUE TITLE
Qual a ideia do projeto?

### ISSUE THREAD

**Issue by gBritz** [CWISoftware/accounts#1]
Descreva a ideia do projeto.

**Comment by Alexandre-Machado** [comment]
A ideia é construir um provedor de oauth2 para as aplicações da CWI.
Irei descrever melhor no README do repositório.

**Comment by gBritz** [comment]
Show, manda ver.
Se tiver alguma coisa para fazer, cadastra umas issues.
Pretendo ajudar, ainda mais na nova versão do framework .net.
