### ISSUE TITLE
continuous integration

### ISSUE THREAD

**Issue by Alexandre-Machado** [CWISoftware/accounts#8]

**Comment by Alexandre-Machado** [comment]
Britz, não consegui acessar o projeto no appveyor. deve ser permissão

**Comment by gBritz** [comment]
Então, acho melhor a empresa ter sua própria conta free para uso em projetos opensource.
Como o que importa é o script em yml, vai ser mumu mudar da minha conta para o da empresa.

**Comment by dwayhs** [comment]
:+1:

**Comment by Alexandre-Machado** [comment]
Pessoal, pelo que vi, a conta do github da CWI pode criar um time no appveyor e delegar as configurações para o time de desenvolvimento do github.
O que acha @brunotrassante ?

**Comment by gBritz** [comment]
Consegui rodar testes nessa nova versão do asp .net 5.
Só vi exemplos com xUnit, o mesmo utilizado no :elephant:. :smile:
Porém, estou tendo dificuldades em configurar a cobertura de código com openCover.
O @sawilde (mantenedor do projeto) deu uma sugestão para solucionar o problema, mas não deu certo.
Mandei outra pergunta:
https://github.com/OpenCover/opencover/issues/327#issuecomment-137356760

**Comment by gBritz** [comment]
Galera, agora temos testes com cobertura e postados no coveralls.
Mais tarde atualizo o readme com o badge.
Uhuuu!!!

**Comment by sawilde** [comment]
:+1:

**Comment by brunotrassante** [comment]
Fechado por mim! Fazemos a integração com o appveyor essa semana ainda!

**Comment by Alexandre-Machado** [comment]
https://ci.appveyor.com/project/contascwi/accounts
